player:
  default_bitrate: auto
  default_size: medium
ui:
  refresh_interval: 300
  theme: dark
  timezone: Europe/Berlin
ultimate_backend:
  timeout: 10
  url: null
webepg:
  timeout: 10
  url: null
